# Generated by Django 6.0.7 on 2026-08-29 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('schedule', '0005_alter_academiccalendarevent_event_type_and_more'),
        ('subject', '0004_subject_is_lab_subject_is_theory'),
        ('timetable', '0008_classtimetable_subject_category_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('FULL_DAY', 'Full Day Leave'), ('HALF_DAY_FN', 'Half Day (Forenoon)'), ('HALF_DAY_AN', 'Half Day (Afternoon)'), ('OD', 'On Duty (OD)'), ('PERMISSION', 'Hourly Permission')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_SUBSTITUTION', 'Pending Substitutions'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_SUBSTITUTION', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, db_column='academic_year_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_applications', to='institution.academicyear')),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='users.user')),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='users.user')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='institution.department')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'faculty_leaves',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Acceptance'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='institution.batch')),
                ('class_timetable', models.ForeignKey(blank=True, db_column='class_timetable_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='timetable.classtimetable')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('day', models.ForeignKey(db_column='day_id', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='schedule.day')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='institution.department')),
                ('original_faculty', models.ForeignKey(db_column='original_faculty_id', on_delete=django.db.models.deletion.CASCADE, related_name='original_substitutions', to='users.user')),
                ('period', models.ForeignKey(db_column='period_id', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='schedule.period')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='institution.section')),
                ('semester', models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='institution.semester')),
                ('subject', models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions', to='subject.subject')),
                ('substitute_faculty', models.ForeignKey(db_column='substitute_faculty_id', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_substitutions', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
                ('leave_application', models.ForeignKey(db_column='leave_application_id', on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='leave.facultyleave')),
            ],
            options={
                'db_table': 'class_substitutions',
                'ordering': ['date', 'period_id'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cl', models.PositiveIntegerField(default=12)),
                ('total_od', models.PositiveIntegerField(default=6)),
                ('total_permissions', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.OneToOneField(db_column='academic_year_id', on_delete=django.db.models.deletion.CASCADE, related_name='leave_policy', to='institution.academicyear')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'leave_policies',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SUBSTITUTION_REQUEST', 'Substitution Request'), ('SUBSTITUTION_RESPONSE', 'Substitution Response'), ('LEAVE_STATUS', 'Leave Status Update'), ('GENERAL', 'General Notice')], default='SUBSTITUTION_REQUEST', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('related_leave', models.ForeignKey(blank=True, db_column='related_leave_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='leave.facultyleave')),
                ('related_substitution', models.ForeignKey(blank=True, db_column='related_substitution_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='leave.classsubstitution')),
                ('sender', models.ForeignKey(blank=True, db_column='sender_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='inbox_notifications', to='users.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
