# Generated by Django 6.0.7 on 2026-09-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        ('student', '0023_hostelvisitorlog'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SUBSTITUTION_REQUEST', 'Substitution Request'), ('SUBSTITUTION_RESPONSE', 'Substitution Response'), ('LEAVE_STATUS', 'Leave Status Update'), ('HOSTEL_LEAVE', 'Hostel Leave Request'), ('GENERAL', 'General Notice')], default='SUBSTITUTION_REQUEST', max_length=30),
        ),
        migrations.CreateModel(
            name='HostelLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_HOSTEL', 'Pending Hostel Approval'), ('PENDING_HOD', 'Pending HOD Approval'), ('APPROVED', 'Approved (Leave Guaranteed)'), ('REJECTED_HOSTEL', 'Rejected by Hostel'), ('REJECTED_HOD', 'Rejected by HOD'), ('CANCELLED', 'Cancelled by Student')], db_index=True, default='PENDING_HOSTEL', max_length=30)),
                ('hostel_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hostel_remarks', models.TextField(blank=True, null=True)),
                ('hod_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hod_remarks', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('hod_approved_by', models.ForeignKey(blank=True, db_column='hod_approved_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_student_leaves', to='users.user')),
                ('hostel_approved_by', models.ForeignKey(blank=True, db_column='hostel_approved_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_approved_student_leaves', to='users.user')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='hostel_leave_requests', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'hostel_leave_requests',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='related_hostel_leave',
            field=models.ForeignKey(blank=True, db_column='related_hostel_leave_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='leave.hostelleaverequest'),
        ),
        migrations.AddIndex(
            model_name='hostelleaverequest',
            index=models.Index(fields=['student', 'status'], name='hostel_leav_student_9d991f_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelleaverequest',
            index=models.Index(fields=['status'], name='hostel_leav_status_193cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelleaverequest',
            index=models.Index(fields=['from_date', 'to_date'], name='hostel_leav_from_da_d31abc_idx'),
        ),
    ]
