# Generated by Django 6.0.7 on 2026-09-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('leave', '0002_alter_notification_notification_type_and_more'),
        ('schedule', '0005_alter_academiccalendarevent_event_type_and_more'),
        ('subject', '0006_sharednotes_shared_note_departm_8a42ae_idx_and_more'),
        ('timetable', '0009_classtimetable_class_timet_faculty_499a9b_idx_and_more'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classsubstitution',
            index=models.Index(fields=['substitute_faculty', 'status', 'date'], name='class_subst_substit_405fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'),
        ),
    ]
