# Generated by Django 6.0.7 on 2026-07-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
