# Generated by Django 6.0.7 on 2026-08-02 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created_at_user_created_by_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Mobile number must be exactly 10 digits.')]),
        ),
    ]
