# Generated by Django 6.0.7 on 2026-08-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
