# Generated by Django 6.0.7 on 2026-08-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0019_alter_feesstructure_unique_together_and_more'),
        ('users', '0007_userdetails_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_details', to='institution.department'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
