# Generated by Django 6.0.7 on 2026-08-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userdetails_department_userdetails_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LEFT', 'Left / Relieved'), ('DISCONTINUED', 'Discontinued'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('ON_LEAVE', 'On Leave')], db_index=True, default='ACTIVE', max_length=30),
        ),
    ]
