# Generated by Django 6.0.7 on 2026-08-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LEFT', 'Left / Relieved'), ('SUSPENDED', 'Suspended'), ('ON_LEAVE', 'On Leave')], db_index=True, default='ACTIVE', max_length=30),
        ),
    ]
