# Generated by Django 6.0.7 on 2026-09-23 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Mobile number must be exactly 10 digits.')]),
        ),
    ]
