# Generated by Django 6.0.7 on 2026-10-09 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0026_student_student_name_alter_student_application'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_type', models.CharField(choices=[('PARENT', 'Parent'), ('STUDENT', 'Student'), ('BOTH', 'Both')], default='PARENT', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('register_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sms_type', models.CharField(default='FULL_DAY_ABSENT', max_length=50)),
                ('template_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('sent_date', models.DateField(help_text='The date of absence or event')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('response_id', models.CharField(blank=True, max_length=150, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('student', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'sms_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sent_date', 'sms_type'], name='sms_logs_sent_da_fd32a6_idx'), models.Index(fields=['student', 'sent_date'], name='sms_logs_student_a2583f_idx'), models.Index(fields=['status'], name='sms_logs_status_3eacc3_idx'), models.Index(fields=['phone_number'], name='sms_logs_phone_n_42b223_idx')],
            },
        ),
    ]
