# Generated by Django 6.0.7 on 2026-09-30 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('industry', models.CharField(choices=[('IT_SOFTWARE', 'Information Technology & Software'), ('FINANCE_BANKING', 'Finance, Banking & Fintech'), ('CORE_ENGINEERING', 'Core Engineering & Manufacturing'), ('HEALTHCARE_PHARMA', 'Healthcare & Pharmaceuticals'), ('ECOMMERCE_RETAIL', 'E-Commerce & Retail'), ('CONSULTING_ANALYTICS', 'Consulting & Business Analytics'), ('EDTECH_EDUCATION', 'Education & EdTech'), ('TELECOM', 'Telecommunications & Networks'), ('LOGISTICS_SUPPLY_CHAIN', 'Logistics & Supply Chain'), ('AUTOMOTIVE', 'Automotive & EV'), ('ENERGY_POWER', 'Energy, Oil & Clean Power'), ('MEDIA_ENTERTAINMENT', 'Media & Entertainment'), ('CONSTRUCTION', 'Civil & Construction'), ('OTHER', 'Other')], db_index=True, default='IT_SOFTWARE', max_length=50)),
                ('company_website', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_person_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('contact_phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'placement_companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_name', 'is_active'], name='placement_c_company_561dd9_idx'), models.Index(fields=['industry', 'is_active'], name='placement_c_industr_96e4bb_idx')],
            },
        ),
    ]
