# Generated by Django 6.0.7 on 2026-09-30 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementcompany',
            name='contact_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='placementcompany',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='placementcompany',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_role', models.CharField(db_index=True, max_length=200)),
                ('drive_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship'), ('INTERNSHIP_PPO', 'Internship + PPO'), ('CONTRACT', 'Contract'), ('APPRENTICESHIP', 'Apprenticeship'), ('OTHER', 'Other')], db_index=True, default='FULL_TIME', max_length=30)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('ctc', models.CharField(blank=True, help_text='e.g., 6.5 LPA, 30,000 / month, Best in Industry', max_length=100, null=True)),
                ('application_start_date', models.DateField(db_index=True)),
                ('application_end_date', models.DateField(db_index=True)),
                ('drive_date', models.DateField(blank=True, db_index=True, null=True)),
                ('document_url', models.URLField(blank=True, help_text='Cloudflare R2 document URL for Job Description/Circular', max_length=600, null=True)),
                ('document_name', models.CharField(blank=True, help_text='Original file name of uploaded JD document', max_length=255, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('REGISTRATION_OPEN', 'Registration Open'), ('REGISTRATION_CLOSED', 'Registration Closed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='UPCOMING', max_length=30)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='placement.placementcompany')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'placement_drives',
                'ordering': ['-application_start_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='placement_d_company_343a15_idx'), models.Index(fields=['drive_type', 'status'], name='placement_d_drive_t_a823a2_idx'), models.Index(fields=['application_start_date', 'application_end_date'], name='placement_d_applica_845593_idx')],
            },
        ),
    ]
