# Generated by Django 6.0.7 on 2026-09-30 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_remove_academicyear_end_date_and_more'),
        ('placement', '0002_alter_placementcompany_contact_email_and_more'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDriveEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum required CGPA (e.g. 6.50, 7.00)', max_digits=4)),
                ('max_backlogs', models.PositiveIntegerField(default=0, help_text='Maximum allowed standing/active backlogs (0 for no backlogs)')),
                ('batches', models.ManyToManyField(blank=True, related_name='placement_eligibilities', to='institution.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('departments', models.ManyToManyField(blank=True, related_name='placement_eligibilities', to='institution.department')),
                ('drive', models.ForeignKey(db_column='drive_id', on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='placement.placementdrive')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'placement_drive_eligibility',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['drive'], name='placement_d_drive_i_55f84e_idx'), models.Index(fields=['minimum_cgpa', 'max_backlogs'], name='placement_d_minimum_19c78a_idx')],
            },
        ),
    ]
