# Generated by Django 6.0.7 on 2026-10-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_placementdriveeligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='no_of_rounds',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of selection rounds', null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='rounds',
            field=models.JSONField(blank=True, default=list, help_text='List of selection round names stored in JSON format', null=True),
        ),
    ]
