# Generated by Django 6.0.7 on 2026-10-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_placementdrive_no_of_rounds_placementdrive_rounds'),
        ('student', '0025_rename_students_applica_idx_students_applica_35e9fa_idx'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlacementTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_status', models.CharField(choices=[('PENDING', 'Pending'), ('PRESENT', 'Present'), ('ABSENT', 'Absent')], db_index=True, default='PENDING', max_length=20)),
                ('cleared_rounds', models.JSONField(blank=True, default=list, help_text="List of cleared rounds (e.g. ['Round 1: Aptitude', 'Round 2: Technical'])", null=True)),
                ('final_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('NOT_ATTENDED', 'Not Attended')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('drive', models.ForeignKey(db_column='drive_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_trackings', to='placement.placementdrive')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='placement_trackings', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'placement_student_trackings',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['drive', 'attendance_status'], name='placement_s_drive_i_2524e3_idx'), models.Index(fields=['drive', 'final_status'], name='placement_s_drive_i_73442f_idx'), models.Index(fields=['student', 'drive'], name='placement_s_student_483095_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'drive'), name='unique_student_placement_drive')],
            },
        ),
    ]
