# Generated by Django 6.0.7 on 2026-10-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_studentplacementtracking'),
        ('student', '0025_rename_students_applica_idx_students_applica_35e9fa_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdriveeligibility',
            name='excluded_students',
            field=models.ManyToManyField(blank=True, related_name='excluded_placement_eligibilities', to='student.student'),
        ),
    ]
