# Generated by Django 6.0.7 on 2026-09-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset'),
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='asset.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_allocations', to='users.user')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_allocations', to='institution.department')),
            ],
            options={
                'db_table': 'asset_allocations',
                'ordering': ['-assigned_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('asset',), name='unique_current_allocation_per_asset')],
            },
        ),
    ]
