# Generated by Django 6.0.7 on 2026-09-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_assetallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetallocation',
            name='location',
        ),
    ]
