# Generated by Django 6.0.7 on 2026-09-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_assettransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
