# Generated by Django 6.0.7 on 2026-09-17 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_assetallocation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('repair', 'Repair'), ('service', 'Service'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=100)),
                ('issue_description', models.TextField()),
                ('maintenance_date', models.DateField()),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('technician_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, choices=[('available', 'Available'), ('assigned', 'Assigned')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='asset.asset')),
            ],
            options={
                'db_table': 'asset_maintenance',
                'ordering': ['-created_at'],
            },
        ),
    ]
