# Generated by Django 6.0.7 on 2026-09-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_assetmaintenance'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_type', models.CharField(choices=[('damaged_beyond_repair', 'Damaged Beyond Repair'), ('obsolete', 'Obsolete'), ('lost', 'Lost'), ('sold', 'Sold'), ('donated', 'Donated'), ('other', 'Other')], max_length=100)),
                ('disposal_date', models.DateField()),
                ('reason', models.TextField()),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approval_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals_approved', to='users.user')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_records', to='asset.asset')),
            ],
            options={
                'db_table': 'asset_disposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
