# Generated by Django 6.0.7 on 2026-10-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_assetdisposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
    ]
