# Generated by Django 6.0.7 on 2026-09-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('institution', '0022_remove_academicyear_end_date_and_more'),
        ('student', '0025_rename_students_applica_idx_students_applica_35e9fa_idx'),
        ('subject', '0008_alter_subject_subject_code_and_more'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityExamHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_capacity', models.PositiveIntegerField(default=25)),
                ('max_capacity', models.PositiveIntegerField(default=27)),
                ('total_seats', models.PositiveIntegerField()),
                ('rows_count', models.PositiveIntegerField()),
                ('columns_count', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('hall', models.OneToOneField(db_column='hall_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_config', to='infrastructure.hall')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'university_exam_halls',
            },
        ),
        migrations.CreateModel(
            name='ExamHallDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_date', models.DateField()),
                ('session', models.CharField(choices=[('FN', 'Forenoon'), ('AN', 'Afternoon')], max_length=2)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
                ('exam_hall', models.ForeignKey(db_column='exam_hall_id', on_delete=django.db.models.deletion.CASCADE, related_name='hall_dates', to='university_exam.universityexamhall')),
            ],
            options={
                'db_table': 'university_exam_hall_dates',
            },
        ),
        migrations.CreateModel(
            name='ExamHallAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_order', models.PositiveIntegerField()),
                ('planned_capacity', models.PositiveIntegerField()),
                ('allocated_students', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ALLOCATED', 'Allocated'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
                ('exam_hall', models.ForeignKey(db_column='exam_hall_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_allocations', to='university_exam.universityexamhall')),
            ],
            options={
                'db_table': 'exam_hall_allocation',
            },
        ),
        migrations.CreateModel(
            name='UniversityExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_date', models.DateField()),
                ('session', models.CharField(choices=[('FN', 'Forenoon'), ('AN', 'Afternoon')], max_length=2)),
                ('qp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_type', models.CharField(default='UNIVERSITY', max_length=50)),
                ('seating_strategy', models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('DEPARTMENT_MIX', 'Department Mix'), ('SUBJECT_MIX', 'Subject Mix'), ('RANDOM', 'Random')], default='DEPARTMENT_MIX', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='university_exam_schedules', to='institution.department')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='university_exam_schedules', to='subject.subject')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'university_exam_schedule',
            },
        ),
        migrations.CreateModel(
            name='UniversityExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('NOT_MARKED', 'Not Marked')], default='NOT_MARKED', max_length=12)),
                ('answer_book_no', models.CharField(blank=True, max_length=50, null=True)),
                ('qp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('attendance_marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='university_exam_attendances', to='institution.department')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='university_exam_attendances', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
                ('exam_schedule', models.ForeignKey(db_column='exam_schedule_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='university_exam.universityexamschedule')),
            ],
            options={
                'db_table': 'university_exam_attendance',
            },
        ),
        migrations.CreateModel(
            name='ExamSeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_number', models.PositiveIntegerField()),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('column_number', models.PositiveIntegerField(blank=True, null=True)),
                ('allocation_status', models.CharField(choices=[('ALLOCATED', 'Allocated'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('CANCELLED', 'Cancelled')], default='ALLOCATED', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='institution.department')),
                ('hall_allocation', models.ForeignKey(db_column='hall_allocation_id', on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='university_exam.examhallallocation')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='student.student')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='subject.subject')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
                ('exam_schedule', models.ForeignKey(db_column='exam_schedule_id', on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='university_exam.universityexamschedule')),
            ],
            options={
                'db_table': 'exam_seat_allocation',
            },
        ),
        migrations.AddField(
            model_name='examhallallocation',
            name='exam_schedule',
            field=models.ForeignKey(db_column='exam_schedule_id', on_delete=django.db.models.deletion.CASCADE, related_name='hall_allocations', to='university_exam.universityexamschedule'),
        ),
        migrations.CreateModel(
            name='ExamAttendanceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college_code', models.CharField(blank=True, max_length=50, null=True)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('register_no', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('session', models.CharField(blank=True, choices=[('FN', 'Forenoon'), ('AN', 'Afternoon')], max_length=2, null=True)),
                ('answer_book_no', models.CharField(blank=True, max_length=50, null=True)),
                ('qp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('import_status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('ERROR', 'Error'), ('IMPORTED', 'Imported')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'exam_attendance_import',
                'indexes': [models.Index(fields=['register_no'], name='exam_attend_registe_4b7bee_idx'), models.Index(fields=['import_status'], name='exam_attend_import__ad573f_idx'), models.Index(fields=['exam_date', 'session'], name='exam_attend_exam_da_1d5cdb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='universityexamhall',
            constraint=models.CheckConstraint(condition=models.Q(('min_capacity__gte', 25), ('max_capacity__lte', 27), ('min_capacity__lte', models.F('max_capacity'))), name='chk_univ_exam_hall_capacity'),
        ),
        migrations.AddConstraint(
            model_name='universityexamhall',
            constraint=models.CheckConstraint(condition=models.Q(('total_seats__gte', models.F('max_capacity'))), name='chk_univ_exam_hall_seats'),
        ),
        migrations.AddIndex(
            model_name='examhalldate',
            index=models.Index(fields=['exam_date', 'session'], name='university__exam_da_cbeef9_idx'),
        ),
        migrations.AddIndex(
            model_name='examhalldate',
            index=models.Index(fields=['exam_hall', 'exam_date'], name='university__exam_ha_fde4d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examhalldate',
            unique_together={('exam_hall', 'exam_date', 'session')},
        ),
        migrations.AddIndex(
            model_name='universityexamschedule',
            index=models.Index(fields=['exam_date', 'session'], name='university__exam_da_c93c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='universityexamschedule',
            index=models.Index(fields=['department', 'exam_date'], name='university__departm_9ca542_idx'),
        ),
        migrations.AddIndex(
            model_name='universityexamschedule',
            index=models.Index(fields=['status'], name='university__status_60f1da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='universityexamschedule',
            unique_together={('department', 'exam_date', 'session', 'subject')},
        ),
        migrations.AddIndex(
            model_name='universityexamattendance',
            index=models.Index(fields=['exam_schedule'], name='university__exam_sc_720705_idx'),
        ),
        migrations.AddIndex(
            model_name='universityexamattendance',
            index=models.Index(fields=['student'], name='university__student_1ea129_idx'),
        ),
        migrations.AddIndex(
            model_name='universityexamattendance',
            index=models.Index(fields=['department'], name='university__departm_700bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='universityexamattendance',
            index=models.Index(fields=['attendance_status'], name='university__attenda_0a7655_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='universityexamattendance',
            unique_together={('exam_schedule', 'student')},
        ),
        migrations.AddIndex(
            model_name='examseatallocation',
            index=models.Index(fields=['exam_schedule'], name='exam_seat_a_exam_sc_c57ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='examseatallocation',
            index=models.Index(fields=['hall_allocation'], name='exam_seat_a_hall_al_1983b9_idx'),
        ),
        migrations.AddIndex(
            model_name='examseatallocation',
            index=models.Index(fields=['student'], name='exam_seat_a_student_67373c_idx'),
        ),
        migrations.AddIndex(
            model_name='examseatallocation',
            index=models.Index(fields=['department'], name='exam_seat_a_departm_719271_idx'),
        ),
        migrations.AddConstraint(
            model_name='examseatallocation',
            constraint=models.UniqueConstraint(fields=('exam_schedule', 'student'), name='unique_seat_per_exam_student'),
        ),
        migrations.AddConstraint(
            model_name='examseatallocation',
            constraint=models.UniqueConstraint(fields=('hall_allocation', 'seat_number'), name='unique_seat_per_hall'),
        ),
        migrations.AddIndex(
            model_name='examhallallocation',
            index=models.Index(fields=['exam_schedule'], name='exam_hall_a_exam_sc_78faab_idx'),
        ),
        migrations.AddConstraint(
            model_name='examhallallocation',
            constraint=models.CheckConstraint(condition=models.Q(('planned_capacity__gte', 25), ('planned_capacity__lte', 27)), name='chk_hall_alloc_planned_capacity'),
        ),
        migrations.AlterUniqueTogether(
            name='examhallallocation',
            unique_together={('exam_schedule', 'exam_hall')},
        ),
    ]
