# Generated by Django 6.0.7 on 2026-09-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('university_exam', '0001_initial'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='universityexamhall',
            name='chk_univ_exam_hall_seats',
        ),
        migrations.AddConstraint(
            model_name='universityexamhall',
            constraint=models.CheckConstraint(condition=models.Q(('total_seats__gte', models.F('min_capacity'))), name='chk_univ_exam_hall_seats'),
        ),
    ]
