# Generated by Django 6.0.7 on 2026-09-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_remove_academicyear_end_date_and_more'),
        ('student', '0025_rename_students_applica_idx_students_applica_35e9fa_idx'),
        ('subject', '0008_alter_subject_subject_code_and_more'),
        ('university_exam', '0002_remove_universityexamhall_chk_univ_exam_hall_seats_and_more'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examattendanceimport',
            name='exam_attend_registe_4b7bee_idx',
        ),
        migrations.AddField(
            model_name='examattendanceimport',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_imports', to='institution.department'),
        ),
        migrations.AddField(
            model_name='examattendanceimport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_imports', to='student.student'),
        ),
        migrations.AddField(
            model_name='examattendanceimport',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_imports', to='subject.subject'),
        ),
        migrations.AddIndex(
            model_name='examattendanceimport',
            index=models.Index(fields=['student'], name='exam_attend_student_2479bd_idx'),
        ),
        migrations.RemoveField(
            model_name='examattendanceimport',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='examattendanceimport',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='examattendanceimport',
            name='college_code',
        ),
        migrations.RemoveField(
            model_name='examattendanceimport',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='examattendanceimport',
            name='register_no',
        ),
        migrations.RemoveField(
            model_name='examattendanceimport',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='examattendanceimport',
            name='subject_code',
        ),
        migrations.RemoveField(
            model_name='examattendanceimport',
            name='subject_name',
        ),
    ]
