# Generated by Django 6.0.7 on 2026-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_exam', '0003_remove_examattendanceimport_exam_attend_registe_4b7bee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examseatallocation',
            name='answer_book_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
