# Generated by Django 6.0.7 on 2026-09-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_exam', '0004_examseatallocation_answer_book_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examseatallocation',
            name='answer_book_no',
        ),
    ]
