# Generated by Django 6.0.7 on 2026-08-29 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0020_alter_section_sections_alter_section_unique_together'),
        ('schedule', '0003_session_alter_period_session'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('DAY_ORDER_SWAP', 'Day Order Swap'), ('HOLIDAY', 'Holiday'), ('SUSPENSION', 'Class Suspension')], max_length=30)),
                ('session_scope', models.CharField(choices=[('FULL_DAY', 'Full Day'), ('FORENOON', 'Forenoon (FN)'), ('AFTERNOON', 'Afternoon (AN)'), ('SPECIFIC_PERIODS', 'Specific Periods')], default='FULL_DAY', max_length=30)),
                ('holiday_category', models.CharField(blank=True, choices=[('RAIN', 'Rain Holiday'), ('GOVERNMENT', 'Government Holiday'), ('FESTIVAL', 'Festival Holiday'), ('INSTITUTIONAL', 'Institutional Holiday'), ('EMERGENCY', 'Emergency Suspension')], max_length=30, null=True)),
                ('title', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, db_column='academic_year_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='institution.academicyear')),
                ('batch', models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='institution.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='institution.department')),
                ('target_day', models.ForeignKey(blank=True, db_column='target_day_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_order_overrides', to='schedule.day')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'academic_calendar_events',
                'ordering': ['-date'],
            },
        ),
    ]
