# Generated by Django 6.0.7 on 2026-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_academiccalendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendarevent',
            name='event_type',
            field=models.CharField(choices=[('DAY_ORDER', 'Working Day Order'), ('DAY_ORDER_SWAP', 'Working Day Order'), ('HOLIDAY', 'Holiday'), ('SUSPENSION', 'Class Suspension')], max_length=30),
        ),
        migrations.AlterField(
            model_name='academiccalendarevent',
            name='holiday_category',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government Holiday'), ('FESTIVAL', 'Festival Holiday'), ('RAIN', 'Rain Holiday'), ('INSTITUTIONAL', 'Institutional Holiday'), ('EMERGENCY', 'Emergency Suspension'), ('OTHER', 'Other Holiday')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='academiccalendarevent',
            name='session_scope',
            field=models.CharField(choices=[('FULL_DAY', 'Full Day'), ('FORENOON', 'Half Day (Forenoon FN)'), ('AFTERNOON', 'Half Day (Afternoon AN)'), ('SPECIFIC_PERIODS', 'Specific Periods')], default='FULL_DAY', max_length=30),
        ),
    ]
