# Generated by Django 6.0.7 on 2026-07-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
    ]
