# Generated by Django 6.0.7 on 2026-10-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['block', 'floor_name']},
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('block', 'floor_name')},
        ),
        migrations.RemoveField(
            model_name='floor',
            name='floor_code',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='floor_order',
        ),
    ]
