# Generated by Django 6.0.7 on 2026-09-11 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('student', '0023_hostelvisitorlog'),
        ('subject', '0006_sharednotes_shared_note_departm_8a42ae_idx_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('PROJECT', 'Project Work'), ('LAB_WORK', 'Lab Work'), ('OTHER', 'Other Task')], default='ASSIGNMENT', max_length=20)),
                ('target_type', models.CharField(choices=[('STUDENT', 'Specific Student'), ('SECTION', 'Section'), ('BATCH', 'Batch'), ('DEPARTMENT', 'Department'), ('ALL', 'All Students')], default='ALL', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lms/reference_attachments/')),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_assignments', to='institution.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_assignments', to='institution.department')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_assignments', to='institution.section')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_assignments', to='subject.subject')),
                ('target_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_lms_assignments', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'lms_assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LMSSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_file', models.FileField(upload_to='lms/student_submissions/')),
                ('student_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('EVALUATED', 'Evaluated / Graded'), ('LATE', 'Late Submission'), ('REJECTED', 'Needs Revision / Rejected')], default='SUBMITTED', max_length=20)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('faculty_feedback', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.lmsassignment')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_lms_submissions', to='users.user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_submissions', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'lms_submission',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
