# Generated by Django 6.0.4 on 2026-09-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsassignment',
            name='attachment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lmssubmission',
            name='submission_file',
            field=models.TextField(),
        ),
    ]
