# Generated by Django 6.0.7 on 2026-09-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('lms', '0002_r2_url_fields'),
        ('subject', '0006_sharednotes_shared_note_departm_8a42ae_idx_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('question_image', models.TextField(blank=True, null=True)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('answer', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='institution.exam')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='subject.subject')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'assessment_questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_code', models.CharField(blank=True, max_length=10, null=True)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lms.assessmentquestion')),
            ],
            options={
                'db_table': 'assessment_options',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['subject', 'exam'], name='assessment__subject_22bf17_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['is_active'], name='assessment__is_acti_62581d_idx'),
        ),
    ]
