# Generated by Django 6.0.7 on 2026-09-22 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('lms', '0003_assessmentquestion_assessmentoption_and_more'),
        ('subject', '0006_sharednotes_shared_note_departm_8a42ae_idx_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assessmentquestion',
            name='assessment__subject_22bf17_idx',
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='question_type',
            field=models.CharField(choices=[('Single Choice', 'Single Choice'), ('Multiple Choice', 'Multiple Choice'), ('True OR False', 'True OR False'), ('File Ups', 'File Ups'), ('Short Answers', 'Short Answers')], default='Single Choice', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='exam',
            field=models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='institution.exam'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['subject', 'question_type'], name='assessment__subject_910f0e_idx'),
        ),
    ]
