# Generated by Django 6.0.7 on 2026-09-23 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('lms', '0004_remove_assessmentquestion_assessment__subject_22bf17_idx_and_more'),
        ('subject', '0006_sharednotes_shared_note_departm_8a42ae_idx_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assessments', to='institution.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lms_assessments', to='users.user')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assessments', to='institution.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assessments', to='institution.regulation')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assessments', to='institution.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assessments', to='institution.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assessments', to='subject.subject')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'lms_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LMSAssessmentQuestionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lms.lmsassessment')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_allocations', to='lms.assessmentquestion')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'lms_assessment_question_item',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='lmsassessment',
            index=models.Index(fields=['department', 'batch', 'section', 'subject'], name='lms_assessm_departm_4aaa60_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsassessment',
            index=models.Index(fields=['is_active'], name='lms_assessm_is_acti_106dc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lmsassessmentquestionitem',
            unique_together={('assessment', 'question')},
        ),
    ]
