# Generated by Django 6.0.7 on 2026-09-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('lms', '0005_lmsassessment_lmsassessmentquestionitem_and_more'),
        ('student', '0023_hostelvisitorlog'),
        ('subject', '0006_sharednotes_shared_note_departm_8a42ae_idx_and_more'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lmsassignment',
            index=models.Index(fields=['department', 'batch', 'section', 'is_active'], name='lms_assignm_departm_b4b589_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsassignment',
            index=models.Index(fields=['is_active', 'due_date'], name='lms_assignm_is_acti_df9224_idx'),
        ),
        migrations.AddIndex(
            model_name='lmssubmission',
            index=models.Index(fields=['assignment', 'student'], name='lms_submiss_assignm_1459cf_idx'),
        ),
        migrations.AddIndex(
            model_name='lmssubmission',
            index=models.Index(fields=['status'], name='lms_submiss_status_c6db6e_idx'),
        ),
    ]
