# Generated by Django 6.0.7 on 2026-09-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_lmsassignment_lms_assignm_departm_b4b589_idx_and_more'),
        ('student', '0023_hostelvisitorlog'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted'), ('EVALUATED', 'Evaluated')], default='IN_PROGRESS', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('attempted_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.lmsassessment')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_assessment_attempts', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'lms_assessment_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LMSAssessmentStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_option_ids', models.JSONField(blank=True, default=list)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='lms.lmsassessmentattempt')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempt_answers', to='lms.assessmentquestion')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'lms_assessment_student_answer',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='lmsassessmentattempt',
            index=models.Index(fields=['assessment', 'student'], name='lms_assessm_assessm_9abd71_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsassessmentattempt',
            index=models.Index(fields=['status'], name='lms_assessm_status_8eb8f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lmsassessmentattempt',
            unique_together={('assessment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='lmsassessmentstudentanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
