# Generated by Django 6.0.7 on 2026-07-30 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_user_created_at_user_created_by_user_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_title', models.CharField(max_length=255)),
                ('notice_type', models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('event', 'Event'), ('fees', 'Fees')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=15)),
                ('publish_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('faculty', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'notice_board',
            },
        ),
    ]
