# Generated by Django 6.0.7 on 2026-09-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='coordinator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='institution.department'),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='organizer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='poster_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='sub_coordinators',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='target_audience_type',
            field=models.CharField(choices=[('global', 'Global (All Departments)'), ('targeted', 'Targeted')], default='global', max_length=20),
        ),
    ]
