# Generated by Django 6.0.7 on 2026-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_noticeboard_batch_noticeboard_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice_type',
            field=models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('holidays', 'Holidays'), ('event', 'Event'), ('events', 'Events'), ('fees', 'Fees')], max_length=20),
        ),
    ]
