# Generated by Django 6.0.7 on 2026-09-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_noticeboard_notice_type'),
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='noticeboard',
            index=models.Index(fields=['is_active', 'expire_date'], name='notice_boar_is_acti_1ae60b_idx'),
        ),
        migrations.AddIndex(
            model_name='noticeboard',
            index=models.Index(fields=['department', 'is_active'], name='notice_boar_departm_97aacf_idx'),
        ),
        migrations.AddIndex(
            model_name='noticeboard',
            index=models.Index(fields=['notice_type'], name='notice_boar_notice__517e58_idx'),
        ),
    ]
