# Generated by Django 6.0.7 on 2026-09-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_title', models.CharField(max_length=300)),
                ('project_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('research_area', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('Funded', 'Funded'), ('Non-Funded', 'Non-Funded'), ('Consultancy', 'Consultancy'), ('Industry Sponsored', 'Industry Sponsored'), ('Institutional', 'Institutional'), ('Other', 'Other')], default='Funded', max_length=50)),
                ('funding_agency', models.CharField(blank=True, max_length=200, null=True)),
                ('sanctioned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Proposed', 'Proposed'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Proposed', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('outcomes', models.TextField(blank=True, null=True)),
                ('co_investigators', models.ManyToManyField(blank=True, related_name='co_research_projects', to='users.userdetails')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_projects', to='institution.department')),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_projects', to='users.userdetails')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'faculty_research_projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
