# Generated by Django 6.0.7 on 2026-09-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresearchproject',
            name='reference_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
