# Generated by Django 6.0.7 on 2026-09-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_facultyresearchproject_reference_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyresearchproject',
            name='department',
        ),
        migrations.AddField(
            model_name='facultyresearchproject',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
