# Generated by Django 6.0.7 on 2026-09-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_remove_facultyresearchproject_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresearchproject',
            name='external_co_investigators',
            field=models.JSONField(blank=True, default=list, help_text='List of external/outer college co-investigators names and affiliations', null=True),
        ),
    ]
