# Generated by Django 6.0.7 on 2026-09-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_facultyresearchproject_external_co_investigators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyresearchproject',
            name='external_co_investigators',
        ),
        migrations.RemoveField(
            model_name='facultyresearchproject',
            name='co_investigators',
        ),
        migrations.AddField(
            model_name='facultyresearchproject',
            name='co_investigators',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of co-investigators containing faculty name, faculty code, etc.', null=True),
        ),
    ]
