# Generated by Django 6.0.7 on 2026-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_remove_facultyresearchproject_external_co_investigators_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyresearchproject',
            name='external_co_investigators',
            field=models.JSONField(blank=True, default=list, help_text='List of external/outer college co-investigators names and affiliations', null=True),
        ),
        migrations.RemoveField(
            model_name='facultyresearchproject',
            name='co_investigators',
        ),
        migrations.AddField(
            model_name='facultyresearchproject',
            name='co_investigators',
            field=models.ManyToManyField(blank=True, related_name='co_research_projects', to='users.userdetails'),
        ),
    ]
