# Generated by Django 6.0.7 on 2026-08-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0015_remove_regulation_academic_year_and_more'),
        ('schedule', '0003_session_alter_period_session'),
        ('users', '0006_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_year', models.ForeignKey(db_column='academic_year_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='institution.academicyear')),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='institution.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='institution.department')),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='institution.exam')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='institution.section')),
                ('semester', models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='institution.semester')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='schedule.session')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'exam_timetables',
            },
        ),
    ]
