# Generated by Django 6.0.7 on 2026-08-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_subject_credits'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtimetable',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='subject.subject'),
        ),
    ]
