# Generated by Django 6.0.7 on 2026-08-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0019_alter_feesstructure_unique_together_and_more'),
        ('schedule', '0003_session_alter_period_session'),
        ('subject', '0004_subject_is_lab_subject_is_theory'),
        ('timetable', '0002_examtimetable_subject'),
        ('users', '0008_userdetails_department_userdetails_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_lab', models.BooleanField(blank=True, default=False)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.ForeignKey(db_column='academic_year_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='institution.academicyear')),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='institution.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('day', models.ForeignKey(db_column='day_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='schedule.day')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='institution.department')),
                ('faculty', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='users.user')),
                ('period', models.ForeignKey(db_column='period_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='schedule.period')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='institution.section')),
                ('semester', models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='institution.semester')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='subject.subject')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'class_timetables',
                'unique_together': {('academic_year', 'day', 'period', 'department', 'batch', 'semester', 'section')},
            },
        ),
    ]
