# Generated by Django 6.0.7 on 2026-08-27 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_subject_is_lab_subject_is_theory'),
        ('timetable', '0003_classtimetable'),
        ('users', '0008_userdetails_department_userdetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetable',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_timetables', to='subject.subject'),
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_name', models.CharField(max_length=100, unique=True)),
                ('display_subject', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'activity_types',
            },
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='activity_type',
            field=models.ForeignKey(blank=True, db_column='activity_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_timetables', to='timetable.activitytype'),
        ),
    ]
