# Generated by Django 6.0.7 on 2026-08-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_classtimetable_subject_activitytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
