# Generated by Django 6.0.7 on 2026-08-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0020_alter_section_sections_alter_section_unique_together'),
        ('schedule', '0003_session_alter_period_session'),
        ('timetable', '0005_classtimetable_from_date_classtimetable_to_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classtimetable',
            unique_together={('academic_year', 'day', 'period', 'department', 'batch', 'semester', 'section', 'from_date')},
        ),
    ]
