# Generated by Django 6.0.7 on 2026-08-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_classtimetable_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtimetable',
            name='is_lab',
        ),
    ]
