# Generated by Django 6.0.7 on 2026-08-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_remove_classtimetable_is_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='subject_category',
            field=models.CharField(blank=True, choices=[('THEORY', 'Theory'), ('LAB', 'Lab')], default='THEORY', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='subject_category',
            field=models.CharField(blank=True, choices=[('THEORY', 'Theory'), ('LAB', 'Lab')], default='THEORY', max_length=20, null=True),
        ),
    ]
