# Generated by Django 6.0.7 on 2026-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('schedule', '0005_alter_academiccalendarevent_event_type_and_more'),
        ('subject', '0006_sharednotes_shared_note_departm_8a42ae_idx_and_more'),
        ('timetable', '0008_classtimetable_subject_category_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classtimetable',
            index=models.Index(fields=['faculty'], name='class_timet_faculty_499a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimetable',
            index=models.Index(fields=['department', 'batch', 'section'], name='class_timet_departm_c7a5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimetable',
            index=models.Index(fields=['day', 'period'], name='class_timet_day_id_f24976_idx'),
        ),
        migrations.AddIndex(
            model_name='examtimetable',
            index=models.Index(fields=['department', 'batch', 'section', 'exam'], name='exam_timeta_departm_f6b543_idx'),
        ),
        migrations.AddIndex(
            model_name='examtimetable',
            index=models.Index(fields=['exam_date'], name='exam_timeta_exam_da_b58716_idx'),
        ),
    ]
