# Generated by Django 6.0.7 on 2026-08-04 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0012_remove_batch_academic_year'),
        ('student', '0001_initial'),
        ('users', '0006_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('register_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('lab_batch', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institution.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institution.department')),
                ('section', models.ForeignKey(blank=True, db_column='section_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='institution.section')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.studentstatus')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.user')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
