# Generated by Django 6.0.7 on 2026-08-04 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0005_alter_applicationuser_phone_number'),
        ('student', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='dynamic_forms.applicationuser'),
        ),
    ]
