# Generated by Django 6.0.7 on 2026-08-06 09:22

import django.db.models.deletion
from django.db import migrations, models


def resolve_duplicate_users(apps, schema_editor):
    Student = apps.get_model('student', 'Student')
    ApplicationUser = apps.get_model('dynamic_forms', 'ApplicationUser')
    
    seen_users = set()
    for student in Student.objects.order_by('id'):
        if student.user_id in seen_users:
            new_user = ApplicationUser.objects.create(
                name=f"Student User {student.roll_number}",
                email=f"student_{student.roll_number}@example.com",
                phone_number="0000000000",
                password="default_password"
            )
            student.user_id = new_user.id
            student.save(update_fields=['user_id'])
        else:
            seen_users.add(student.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0005_alter_applicationuser_phone_number'),
        ('student', '0003_alter_student_user'),
    ]

    operations = [
        migrations.RunPython(resolve_duplicate_users, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='dynamic_forms.applicationuser'),
        ),
    ]

