# Generated by Django 6.0.7 on 2026-08-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0015_remove_regulation_academic_year_and_more'),
        ('student', '0005_marks'),
        ('users', '0006_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField()),
                ('remarks', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('semester', models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, related_name='counselling_reports', to='institution.semester')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='counselling_reports', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'counselling_reports',
            },
        ),
    ]
