# Generated by Django 6.0.7 on 2026-08-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0018_department_is_display'),
        ('student', '0006_counsellingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus_from',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bus_to',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_bus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_day_scholar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_hostler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='quota',
            field=models.ForeignKey(blank=True, db_column='quota_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='institution.quota'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
