# Generated by Django 6.0.7 on 2026-08-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_bus_from_student_bus_to_student_is_bus_and_more'),
        ('users', '0007_userdetails_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(default='Cash', max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('emis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('umis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('certificates_surrendered', models.JSONField(default=dict)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('community', models.CharField(blank=True, max_length=50, null=True)),
                ('marks_maths', models.IntegerField(blank=True, null=True)),
                ('marks_physics', models.IntegerField(blank=True, null=True)),
                ('marks_chemistry', models.IntegerField(blank=True, null=True)),
                ('marks_total', models.IntegerField(blank=True, null=True)),
                ('marks_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mode_of_admission', models.CharField(default='I Sem', max_length=50)),
                ('tuition_fees_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_fees_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tuition_fees_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_fees_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('student', models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='fees_payment', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'students_fees',
            },
        ),
    ]
