# Generated by Django 6.0.7 on 2026-08-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentfees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfees',
            name='other_fees_balance',
        ),
        migrations.RemoveField(
            model_name='studentfees',
            name='other_fees_paid',
        ),
        migrations.RemoveField(
            model_name='studentfees',
            name='tuition_fees_balance',
        ),
        migrations.RemoveField(
            model_name='studentfees',
            name='tuition_fees_paid',
        ),
    ]
