# Generated by Django 6.0.7 on 2026-08-19 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_studentfees_other_fees_balance_and_more'),
        ('users', '0007_userdetails_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfees',
            name='books_fees_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfees',
            name='books_fees_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfees',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfees',
            name='recommendation',
            field=models.ForeignKey(blank=True, db_column='recommendation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_students', to='users.user'),
        ),
    ]
