# Generated by Django 6.0.7 on 2026-08-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_split_studentfees'),
        ('users', '0007_userdetails_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmissionslip',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user'),
        ),
        migrations.AlterField(
            model_name='studentadmissionslip',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user'),
        ),
    ]
