# Generated by Django 6.0.7 on 2026-08-27 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_studentadmissionslip_created_by_and_more'),
        ('timetable', '0003_classtimetable'),
        ('users', '0008_userdetails_department_userdetails_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('activity_type', models.CharField(choices=[('lecture', 'Lecture'), ('laboratory', 'Laboratory'), ('discussion', 'Discussion'), ('test_or_exam', 'Test or exam'), ('seminar', 'Seminar'), ('others', 'Others')], max_length=30)),
                ('other_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_students', models.IntegerField(default=0)),
                ('total_present', models.IntegerField(default=0)),
                ('total_absentees', models.IntegerField(default=0)),
                ('total_od', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('timetable', models.ForeignKey(db_column='timetable_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='timetable.classtimetable')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'faculty_activities',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('AB', 'Absent'), ('OD', 'On Duty')], default='P', max_length=5)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('faculty_activity', models.ForeignKey(db_column='faculty_activity_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student.facultyactivity')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'student_attendances',
                'unique_together': {('faculty_activity', 'student')},
            },
        ),
    ]
