# Generated by Django 6.0.7 on 2026-08-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0020_alter_section_sections_alter_section_unique_together'),
        ('student', '0013_facultyactivity_studentattendance'),
        ('subject', '0004_subject_is_lab_subject_is_theory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marks',
            name='subject_category',
            field=models.CharField(blank=True, choices=[('THEORY', 'Theory'), ('LAB', 'Lab')], default='THEORY', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'exam', 'subject', 'subject_category')},
        ),
    ]
