# Generated by Django 6.0.7 on 2026-08-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_marks_unique_together_marks_subject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyactivity',
            name='status',
            field=models.CharField(choices=[('CONDUCTED', 'Conducted'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('HOLIDAY', 'Holiday')], default='CONDUCTED', max_length=20),
        ),
        migrations.AddField(
            model_name='facultyactivity',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
