# Generated by Django 6.0.7 on 2026-09-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_facultyactivity_status_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(help_text='Grade letter e.g., O, A+, A, B+, B, C, P, F, RA', max_length=10, unique=True)),
                ('points', models.DecimalField(decimal_places=2, help_text='Grade points e.g., 10.0, 9.0, 8.0', max_digits=5)),
                ('min_mark', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum mark threshold', max_digits=5, null=True)),
                ('max_mark', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum mark threshold', max_digits=5, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'grade_system',
                'ordering': ['-points'],
            },
        ),
    ]
