# Generated by Django 6.0.7 on 2026-09-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_gradesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesystem',
            name='is_pass',
            field=models.BooleanField(default=True, help_text='Designates passing grade/range'),
        ),
    ]
