# Generated by Django 6.0.7 on 2026-09-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_gradesystem_is_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bus_from',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bus_to',
        ),
    ]
