# Generated by Django 6.0.7 on 2026-09-08 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_remove_student_bus_from_remove_student_bus_to'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus',
            field=models.ForeignKey(blank=True, db_column='bus_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.bus'),
        ),
        migrations.AddField(
            model_name='student',
            name='route',
            field=models.ForeignKey(blank=True, db_column='route_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.transportroute'),
        ),
        migrations.AddField(
            model_name='student',
            name='stop',
            field=models.ForeignKey(blank=True, db_column='stop_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.routestop'),
        ),
    ]
