# Generated by Django 6.0.7 on 2026-09-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_student_bus_student_route_student_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hostel_building_type',
            field=models.CharField(blank=True, choices=[('BOYS', 'Boys Hostel'), ('GIRLS', 'Girls Hostel'), ('COMBINED', 'Combined')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
