# Generated by Django 6.0.7 on 2026-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0007_seed_application_statuses'),
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('student', '0020_student_hostel_building_type_and_more'),
        ('subject', '0005_sharednotes'),
        ('transport', '0004_transportexpense_incharge_driver'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['student', 'exam'], name='marks_student_47a21b_idx'),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['exam', 'subject'], name='marks_exam_id_156cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department', 'batch', 'section'], name='students_departm_71f0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_bus', 'bus'], name='students_is_bus_3f9743_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_hostler'], name='students_is_host_eadb99_idx'),
        ),
    ]
