# Generated by Django 6.0.7 on 2026-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0007_seed_application_statuses'),
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('student', '0021_marks_marks_student_47a21b_idx_and_more'),
        ('subject', '0005_sharednotes'),
        ('timetable', '0008_classtimetable_subject_category_and_more'),
        ('transport', '0004_transportexpense_incharge_driver'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='counsellingreport',
            index=models.Index(fields=['student', 'report_date'], name='counselling_student_a698b8_idx'),
        ),
        migrations.AddIndex(
            model_name='counsellingreport',
            index=models.Index(fields=['semester'], name='counselling_semeste_0ea5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyactivity',
            index=models.Index(fields=['timetable', 'date'], name='faculty_act_timetab_3997fc_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyactivity',
            index=models.Index(fields=['date'], name='faculty_act_date_2ab954_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyactivity',
            index=models.Index(fields=['status'], name='faculty_act_status_2ad991_idx'),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['student', 'subject'], name='marks_student_572e74_idx'),
        ),
        migrations.AddIndex(
            model_name='marks',
            index=models.Index(fields=['created_by'], name='marks_created_350104_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_status__8d2e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['quota'], name='students_quota_i_224218_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user'], name='students_user_id_b061ff_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_number'], name='students_roll_nu_954626_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['register_number'], name='students_registe_5bdfab_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['faculty_activity', 'status'], name='student_att_faculty_396f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'status'], name='student_att_student_be1c2f_idx'),
        ),
    ]
