# Generated by Django 6.0.7 on 2026-09-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_counsellingreport_counselling_student_a698b8_idx_and_more'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelVisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('GUARDIAN', 'Guardian'), ('FRIEND', 'Friend'), ('RELATIVE', 'Relative'), ('OTHERS', 'Others')], max_length=30)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('reason_of_visit', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'hostel_visitor_logs',
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['student', 'check_in'], name='hostel_visi_student_9f48b3_idx'), models.Index(fields=['check_in'], name='hostel_visi_check_i_7d9e51_idx')],
            },
        ),
    ]
