# Generated by Django 6.0.7 on 2026-09-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_student_application'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='students_applica_35e9fa_idx',
            old_name='students_applica_idx',
        ),
    ]
