# Generated by Django 6.0.7 on 2026-10-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0011_alter_paymenttransaction_application'),
        ('student', '0025_rename_students_applica_idx_students_applica_35e9fa_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='application',
            field=models.OneToOneField(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='dynamic_forms.application'),
        ),
    ]
