# Generated by Django 6.0.7 on 2026-10-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0023_normalize_semester'),
        ('student', '0026_student_student_name_alter_student_application'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySpecialDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('session_scope', models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY_FN', 'Half Day (Forenoon)'), ('HALF_DAY_AN', 'Half Day (Afternoon)'), ('SPECIFIC_PERIODS', 'Specific Periods')], default='FULL_DAY', max_length=30)),
                ('periods', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(choices=[('OD', 'On Duty (OD)'), ('PARENTS_MEETING', 'Parents-Teachers Meeting (PTM)'), ('DEPT_WORK', 'Department / NAAC / NBA Work'), ('EXAM_DUTY', 'Exam / Valuation Duty'), ('EVENT', 'Symposium / Workshop / College Event'), ('ADMISSION', 'Admission Duty'), ('OTHERS', 'Others / Special Work')], default='OD', max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('reference_no', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_special_duties', to='institution.department')),
                ('faculty', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, related_name='special_duties', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'faculty_special_duties',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['faculty', 'date'], name='faculty_spe_faculty_57865c_idx'), models.Index(fields=['department', 'date'], name='faculty_spe_departm_4e57c4_idx')],
            },
        ),
    ]
