# Generated by Django 6.0.7 on 2026-10-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0023_normalize_semester'),
        ('student', '0027_facultyspecialduty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyspecialduty',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_special_duties', to='institution.department'),
        ),
    ]
