# Generated by Django 6.0.7 on 2026-07-29 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institution.program')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
