# Generated by Django 6.0.7 on 2026-07-29 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_academicyear_program_no_of_years_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='academic_year',
            field=models.ForeignKey(blank=True, db_column='academic_year_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='institution.academicyear'),
        ),
    ]
