# Generated by Django 6.0.7 on 2026-07-29 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_batch_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(db_column='academic_year_id', on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='institution.academicyear')),
            ],
            options={
                'db_table': 'regulation',
            },
        ),
    ]
