# Generated by Django 6.0.7 on 2026-07-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_regulation'),
        ('users', '0003_delete_userotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='no_of_years',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, db_column='hod_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_departments', to='users.user'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_level',
            field=models.CharField(choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('PhD', 'Doctor of Philosophy'), ('Diploma', 'Diploma')], default='UG', max_length=20),
            preserve_default=False,
        ),
    ]
