# Generated by Django 6.0.7 on 2026-07-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_rename_no_of_years_program_duration_department_hod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
