# Generated by Django 6.0.7 on 2026-07-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0009_section'),
        ('users', '0004_user_created_at_user_created_by_user_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('header_type', models.CharField(max_length=100, unique=True)),
                ('primary_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('secondary_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'college_header',
            },
        ),
    ]
