# Generated by Django 6.0.7 on 2026-08-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0011_examtype_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='academic_year',
        ),
    ]
