# Generated by Django 6.0.7 on 2026-08-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0012_remove_batch_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
