# Generated by Django 6.0.7 on 2026-08-06 12:45

from django.db import migrations


def resolve_duplicate_batches(apps, schema_editor):
    Batch = apps.get_model('institution', 'Batch')
    Student = apps.get_model('student', 'Student')
    
    seen = {}
    for batch_obj in Batch.objects.order_by('id'):
        key = (batch_obj.department_id, batch_obj.batch.strip().lower())
        if key in seen:
            primary_batch_id = seen[key]
            Student.objects.filter(batch_id=batch_obj.id).update(batch_id=primary_batch_id)
            batch_obj.delete()
        else:
            seen[key] = batch_obj.id


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0013_academicyear_is_display'),
    ]

    operations = [
        migrations.RunPython(resolve_duplicate_batches, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('department', 'batch')},
        ),
    ]

