# Generated by Django 6.0.7 on 2026-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0014_alter_batch_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulation',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='regulation',
            name='effective_from_year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
