# Generated by Django 6.0.7 on 2026-08-12 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0016_quota'),
        ('users', '0006_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academic_year', models.ForeignKey(db_column='academic_year_id', on_delete=django.db.models.deletion.CASCADE, related_name='fees_structures', to='institution.academicyear')),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='fees_structures', to='institution.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='fees_structures', to='institution.department')),
                ('quota', models.ForeignKey(db_column='quota_id', on_delete=django.db.models.deletion.CASCADE, related_name='fees_structures', to='institution.quota')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'fees_structure',
                'unique_together': {('academic_year', 'department', 'batch', 'quota')},
            },
        ),
    ]
