# Generated by Django 6.0.7 on 2026-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0017_feesstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
