# Generated by Django 6.0.7 on 2026-08-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0018_department_is_display'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feesstructure',
            unique_together={('department', 'batch', 'quota')},
        ),
        migrations.RemoveField(
            model_name='feesstructure',
            name='academic_year',
        ),
    ]
