# Generated by Django 6.0.7 on 2026-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0019_alter_feesstructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sections',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('department', 'sections')},
        ),
    ]
