# Generated by Django 6.0.7 on 2026-08-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0020_alter_section_sections_alter_section_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='even_sem_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='even_sem_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='odd_sem_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='odd_sem_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
