# Generated by Django 6.0.7 on 2026-09-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='even_sem_end_date',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='even_sem_start_date',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='odd_sem_end_date',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='odd_sem_start_date',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='start_date',
        ),
    ]
