# Generated by Django on 2026-10-09

from django.db import migrations, models
import django.db.models.deletion


def populate_normalized_semesters(apps, schema_editor):
    Department = apps.get_model('institution', 'Department')
    Semester = apps.get_model('institution', 'Semester')

    departments = Department.objects.all()
    for dept in departments:
        # Determine number of semesters based on program level
        prog = getattr(dept, 'program', None)
        prog_level = (getattr(prog, 'program_level', '') or '').upper()
        prog_name = (getattr(prog, 'program_name', '') or '').upper()

        if 'PG' in prog_level or 'M.E' in prog_name or 'MCA' in prog_name or 'MBA' in prog_name:
            sem_count = 4
        else:
            sem_count = 8

        # Check existing semester records for this department
        existing_sems = list(Semester.objects.filter(department=dept).order_by('id'))

        for sem_num in range(1, sem_count + 1):
            sem_name = f"Semester {sem_num}"
            if existing_sems and sem_num == 1:
                # Update first existing record to be Semester 1
                first_sem = existing_sems[0]
                first_sem.semester_number = 1
                first_sem.semester_name = sem_name
                first_sem.save(update_fields=['semester_number', 'semester_name'])
            else:
                # Check if a semester with this number already exists or create new
                existing_match = Semester.objects.filter(department=dept, semester_number=sem_num).first()
                if not existing_match:
                    Semester.objects.create(
                        department=dept,
                        semester_number=sem_num,
                        semester_name=sem_name,
                        created_by=dept.created_by,
                        updated_by=dept.updated_by
                    )


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_remove_academicyear_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['department', 'semester_number']},
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(default='Semester 1', max_length=50),
        ),
        migrations.RunPython(
            populate_normalized_semesters,
            reverse_code=reverse_populate,
        ),
        migrations.RemoveField(
            model_name='semester',
            name='semesters',
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('department', 'semester_number'), name='unique_department_semester_number'),
        ),
    ]
