# Generated by Django 6.0.7 on 2026-08-03 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0012_remove_batch_academic_year'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institution.semester'),
        ),
    ]
