# Generated by Django 6.0.7 on 2026-08-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_alter_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.FloatField(),
        ),
    ]
