# Generated by Django 6.0.7 on 2026-08-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_subject_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_theory',
            field=models.BooleanField(default=True),
        ),
    ]
