# Generated by Django 6.0.7 on 2026-09-01 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('subject', '0004_subject_is_lab_subject_is_theory'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(max_length=50)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to='institution.batch')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to='institution.department')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to='institution.section')),
                ('semester', models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to='institution.semester')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to='subject.subject')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_notes', to='users.user')),
            ],
            options={
                'db_table': 'shared_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
