# Generated by Django 6.0.7 on 2026-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_academicyear_even_sem_end_date_and_more'),
        ('subject', '0005_sharednotes'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sharednotes',
            index=models.Index(fields=['department', 'batch', 'semester', 'section'], name='shared_note_departm_8a42ae_idx'),
        ),
        migrations.AddIndex(
            model_name='sharednotes',
            index=models.Index(fields=['subject'], name='shared_note_subject_44e528_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department', 'regulation'], name='subjects_departm_b466c4_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department', 'semester'], name='subjects_departm_9e210f_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='subjects_is_acti_960049_idx'),
        ),
    ]
