# Generated by Django 6.0.7 on 2026-09-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_sharednotes_shared_note_departm_8a42ae_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_type',
            field=models.CharField(blank=True, choices=[('PCC', 'Professional Core Course (PCC)'), ('PEC', 'Professional Elective Course (PEC)'), ('OEC', 'Open Elective Course (OEC)'), ('MC', 'Mandatory Course (MC)'), ('EEC', 'Employability Enhancement / Skill Development (EEC)'), ('HSMC', 'Humanities, Social Sciences & Management (HSMC)'), ('BSC', 'Basic Science Course (BSC)'), ('ESC', 'Engineering Science Course (ESC)'), ('AC', 'Audit Course (AC)'), ('VAC', 'Value Added Course (VAC)')], default='PCC', max_length=50, null=True),
        ),
    ]
