# Generated by Django 6.0.7 on 2026-09-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_remove_academicyear_end_date_and_more'),
        ('subject', '0007_subject_course_type'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subject_code', 'regulation', 'department', 'semester'), name='unique_subject_curriculum'),
        ),
    ]
