# Generated by Django 6.0.7 on 2026-09-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_remove_academicyear_end_date_and_more'),
        ('subject', '0008_alter_subject_subject_code_and_more'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_curriculum',
        ),
        migrations.AlterField(
            model_name='subject',
            name='course_type',
            field=models.CharField(blank=True, choices=[('PCC', 'Professional Core Course (PCC)'), ('PEC', 'Professional Elective Course (PEC)'), ('OEC', 'Open Elective Course (OEC)'), ('MC', 'Mandatory Course (MC)'), ('EEC', 'Employability Enhancement / Skill Development (EEC)'), ('HSMC', 'Humanities, Social Sciences & Management (HSMC)'), ('BSC', 'Basic Science Course (BSC)'), ('ESC', 'Engineering Science Course (ESC)'), ('AC', 'Audit Course (AC)'), ('VAC', 'Value Added Course (VAC)')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_code__isnull', False), models.Q(('subject_code', ''), _negated=True)), fields=('subject_code', 'regulation', 'department', 'semester'), name='unique_subject_curriculum'),
        ),
    ]
