# Generated by Django 6.0.7 on 2026-09-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_remove_academicyear_end_date_and_more'),
        ('subject', '0009_remove_subject_unique_subject_curriculum_and_more'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_curriculum',
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subject_code', 'regulation', 'department', 'semester'), name='unique_subject_curriculum'),
        ),
    ]
