# Generated by Django 6.0.7 on 2026-10-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0010_remove_subject_unique_subject_curriculum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course_type',
        ),
    ]
