# Generated by Django 6.0.7 on 2026-08-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0003_application_program_applicationstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationuser',
            old_name='student_name',
            new_name='name',
        ),
    ]
