# Generated by Django 6.0.7 on 2026-08-02 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0004_rename_student_name_applicationuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be exactly 10 digits.')]),
        ),
    ]
