# Generated by Django 6.0.7 on 2026-08-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0005_alter_applicationuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('select', 'Select Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('textarea', 'Text Area'), ('file', 'File Upload'), ('array', 'Array')], max_length=30),
        ),
    ]
