# Generated by Django 6.0.7

from django.db import migrations

def seed_statuses(apps, schema_editor):
    ApplicationStatus = apps.get_model('dynamic_forms', 'ApplicationStatus')
    statuses = ['Submitted', 'Approved', 'Rejected', 'Waiting List']
    for status in statuses:
        ApplicationStatus.objects.get_or_create(status_name=status)

def remove_statuses(apps, schema_editor):
    ApplicationStatus = apps.get_model('dynamic_forms', 'ApplicationStatus')
    statuses = ['Submitted', 'Approved', 'Rejected', 'Waiting List']
    ApplicationStatus.objects.filter(status_name__in=statuses).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0006_alter_formfield_field_type'),
    ]

    operations = [
        migrations.RunPython(seed_statuses, remove_statuses),
    ]
