# Generated by Django 6.0.7 on 2026-09-23 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0007_seed_application_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be exactly 10 digits.')]),
        ),
    ]
