# Generated by Django 6.0.7 on 2026-09-25 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0008_alter_applicationuser_phone_number'),
        ('institution', '0022_remove_academicyear_end_date_and_more'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, db_column='academic_year_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_fees', to='institution.academicyear')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('program', models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_fees', to='institution.program')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'application_fees',
                'ordering': ['-id'],
            },
        ),
    ]
