# Generated by Django 6.0.7 on 2026-09-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, db_column='route_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='transport.transportroute'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='fuel_type',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRIC', 'Electric'), ('CNG', 'CNG'), ('HYBRID', 'Hybrid')], default='DIESEL', max_length=20),
        ),
    ]
