# Generated by Django 6.0.7 on 2026-09-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_bus_is_active_bus_route_alter_bus_fuel_type'),
        ('users', '0010_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('fuel', 'Fuel'), ('service', 'Service'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('tyre', 'Tyre'), ('battery', 'Battery'), ('insurance', 'Insurance'), ('tax', 'Tax'), ('permit', 'Permit'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=50)),
                ('expense_date_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('vendor', models.CharField(max_length=200)),
                ('odometer_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_number', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=50)),
                ('bus', models.ForeignKey(db_column='bus_id', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='transport.bus')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to='users.user')),
            ],
            options={
                'db_table': 'transport_expense',
                'ordering': ['-expense_date_time'],
            },
        ),
    ]
