# Generated by Django 6.0.7 on 2026-09-09 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_transportexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportexpense',
            name='incharge_driver',
            field=models.ForeignKey(blank=True, db_column='incharge_driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge_expenses', to='transport.driver'),
        ),
    ]
