# Generated by Django 6.0.7 on 2026-09-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_transportexpense_incharge_driver'),
        ('users', '0011_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transportexpense',
            index=models.Index(fields=['bus', 'expense_date_time'], name='transport_e_bus_id_174a12_idx'),
        ),
    ]
